sudo: false

language: node_js
node_js:
- '6'
- '7'

cache:
  directories:
    - node_modules

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_script:
  - npm run build

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5
